services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - cookix-network

  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - cookix_db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    networks:
      - cookix-network

  scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    restart: always
    volumes:
      - playwright-browsers:/ms-playwright
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - cookix-network

networks:
  cookix-network:
    driver: bridge

volumes:
  cookix_db_data:
  playwright-browsers: