name: Deploy Cookix
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Install scraper dependencies
        run: |
          cd scripts/scraper
          npm ci
          cd ../..
      
      - name: Generate Prisma Client
        run: npx prisma generate
        
      - name: Build project
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.OVH_SSH_KEY }}
          known_hosts: 'placeholder'
          
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.OVH_SERVER_HOST }} >> ~/.ssh/known_hosts
      
      - name: Create .env file
        run: |
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "ROOT_PASSWORD=${{ secrets.ROOT_PASSWORD }}" >> .env
          echo "DATABASE_URL="mysql://${secrets.DB_USER}:${secrets.DB_PASSWORD}@db:3306/${secrets.DB_NAME}" > .env
      
      - name: Copy configuration and build files
        run: |
          rsync -avz .env ${{ secrets.OVH_SERVER_USER }}@${{ secrets.OVH_SERVER_HOST }}:/var/www/cookix/
          rsync -avz --exclude 'node_modules' --exclude '.git' ./ ${{ secrets.OVH_SERVER_USER }}@${{ secrets.OVH_SERVER_HOST }}:/var/www/cookix/

      - name: Start docker
        run: |
          ssh ${{ secrets.OVH_SERVER_USER }}@${{ secrets.OVH_SERVER_HOST }} 'ls /var/www/cookix/'