name: E2E Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Create .env file
        run: |
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" > .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "ROOT_PASSWORD=${{ secrets.ROOT_PASSWORD }}" >> .env
          echo "DATABASE_URL=mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@db:3306/${{ secrets.DB_NAME }}" >> .env

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Docker containers for testing
        run: docker compose up -d --build  

      - name: Run E2E tests
        run: docker compose exec -ti app npx playwright install chromium

      - name: Run E2E tests
        run: docker compose exec -ti app npx playwright test

      - name: Show logs in case of failure
        if: failure()
        run: docker compose logs

      - name: Copy test reports from container
        if: always()
        run: |
            # Créer un répertoire local pour les rapports
            mkdir -p test-results
            # Copier les rapports depuis le conteneur
            docker compose cp app:/app/test-results ./

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 30

      - name: Cleanup
        if: always()
        run: docker compose down