name: E2E Tests

on:
  push:
    branches: [master]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        
      - name: Create .env file
        run: |
          ssh ${{ secrets.OVH_SERVER_USER }}@${{ secrets.OVH_SERVER_HOST }} 'cd /var/www/cookix && echo "
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          ROOT_PASSWORD=${{ secrets.ROOT_PASSWORD }}
          DATABASE_URL=mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@db:3306/${{ secrets.DB_NAME }}
          " > .env'

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Docker containers for testing
        run: npm run build

      - name: Wait for services to be ready
        run: |
          # Attendre que l'application soit prête
          npx wait-on http://localhost:3000 -t 60000 || (docker compose logs && exit 1)

      - name: Run E2E tests
        run: npx playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Cleanup
        if: always()
        run: docker compose down